//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CompDel.rc
//
#define IDC_INSTHLP                     3
#define IDD_COMPDEL_DIALOG              102
#define IDD_DLG_PROPDISP                107
#define IDR_MAINFRAME                   128
#define IDD_DLG_NORMAL                  138
#define IDD_DLG_ABOUT                   139
#define IDD_DLG_CONFF                   145
#define IDD_DLG_PROPDEL                 147
#define IDD_DLG_PROPOTHER               148
#define IDD_DLG_INSTALL                 149
#define IDI_ICO_INST                    150
#define IDD_DLG_HELPDOC                 151
#define IDD_DLG_PROPDEL2                152
#define IDD_DLG_PROPDEL3                154
#define IDI_ICO_VI1                     158
#define IDI_ICO_2K2                     159
#define IDI_ICO_952                     160
#define IDI_ICO_951                     161
#define IDI_ICO_VI2                     162
#define IDI_ICO_2K1                     163
#define IDC_C_NDISPN                    1002
#define IDC_C_NDISPE                    1003
#define IDC_C_DATE                      1004
#define IDC_R1_NULL                     1005
#define IDC_R2_ZLEN                     1006
#define IDC_R1_RND                      1007
#define IDC_R2_RLEN                     1008
#define IDC_R3_RNAME                    1009
#define IDC_R3_SNAME                    1010
#define IDC_C_DMY                       1011
#define IDC_R3_NNAME                    1011
#define IDC_C_DISPC                     1012
#define IDC_R1_DOD                      1012
#define IDC_LFNAME                      1014
#define IDC_PRGRESS                     1015
#define IDC_C_DMYSKIP                   1015
#define IDC_MES                         1016
#define IDC_C_DISPF                     1016
#define IDC_C_DISPF2                    1017
#define IDC_EDIT_NTIMES                 1025
#define IDC_MESSAGE                     1026
#define IDC_VERINFO                     1028
#define IDC_UNINSTALL                   1030
#define IDC_INSTALL                     1031
#define IDC_UNINSTALL2                  1031
#define IDC_UNINSTALL3                  1032
#define IDC_C_RECFOLDER                 1033
#define IDC_INST_DESKTOP                1034
#define IDC_UNINSTALL4                  1034
#define IDC_INST_CONTEXT                1035
#define IDC_EDIT_NFILES                 1035
#define IDC_RADIO_UNIN                  1036
#define IDC_RADIO_UNIN2                 1037
#define IDC_EDIT_MAIN                   1037
#define IDC_INST_MENU                   1038
#define IDC_EDIT1                       1038
#define IDC_EDIT_TEXTEDITOR             1038
#define IDC_EDIT2                       1039
#define IDC_C_UNTICACHE                 1040
#define IDC_R1_UNTIDIR                  1041
#define IDC_R1_UNTIDIR2                 1042
#define IDC_EDIT_UNTISIZE               1043
#define IDC_EDIT_BUFFER                 1044
#define IDC_EDIT_OVERRUN                1045
#define IDC_EDIT_DODCHAR                1046
#define IDC_C_ANTICACHE                 1047
#define IDC_R1_ANTIDIR                  1048
#define IDC_R1_ANTIDIR2                 1049
#define IDC_EDIT_ANTISIZE               1050
#define IDC_EDIT_DUMMY_NFILES           1051
#define IDC_EDIT_QUICK_FNAME            1052
#define IDC_C_ANTI_ONETIME              1052
#define IDC_BTN_QFILE_BROWSE            1053
#define IDC_BTN_QEXEC                   1054
#define IDC_BTN_QFILE_BROWSE2           1055
#define IDC_C_NOTREMOVE                 1056
#define AFX_STR_UNINST_CPLNAME          57345
#define AFX_STR_LINK_UNINST             57346
#define AFX_STR_LINK_STARTUP            57347
#define AFX_STR_LINK_PROG               57348
#define AFX_STR_DBG_ATTR                57349
#define AFX_STR_DBG_OVER                57350
#define AFX_STR_DBG_ZEROLEN             57351
#define AFX_STR_DBG_FNAME               57352
#define AFX_STR_DBG_WINNAME             57353
#define AFX_STR_DBG_DATE                57354
#define AFX_STR_DBG_DELETE              57355
#define AFX_STR_DBG_MKDUMMY             57356
#define AFX_STR_DBG_DLDUMMY             57357
#define AFX_STR_LOG_DUMMY               57358
#define AFX_STR_LOG_COMPLETE            57359
#define AFX_STR_LOG_SUCCESS             57360
#define AFX_STR_LOG_FAIL                57361
#define AFX_STR_LOG_INIT1               57362
#define AFX_STR_LOG_INIT2               57363
#define AFX_STR_LOG_INIT3               57364
#define AFX_STR_LOG_INIT4               57365
#define AFX_STR_DLG_EXCLUDE             57366
#define AFX_STR_LOG_EXCLUDE             57367
#define AFX_STR_DLG_PRGRS               57368
#define AFX_STR_ERR_0                   57369
#define AFX_STR_ERR_1                   57370
#define AFX_STR_ERR_2                   57371
#define AFX_STR_ERR_3                   57372
#define AFX_STR_ERR_4                   57373
#define AFX_STR_ERR_5                   57374
#define AFX_STR_ERR_6                   57375
#define AFX_STR_ERR_7                   57376
#define AFX_STR_ERR_8                   57377
#define AFX_STR_ERR_9                   57378
#define AFX_STR_ERR_N                   57379
#define AFX_STR_DLG_ERRCAUSE            57380
#define AFX_STR_UNIN_CONFERM            57381
#define AFX_STR_MAINDLG                 57382
#define AFX_STR_DLG_CONFIRM             57383
#define AFX_STR_DLG_PRGRS_2             57384
#define AFX_STR_DLG_PRGRS_3             57385
#define AFX_STR_DLG_MKUNIN              57386
#define AFX_STR_DBG_OVERRUN             57387
#define AFX_STR_DBG_ANTICACHE           57388
#define AFX_STR_ERR_ANTICACHE           57389
#define AFX_STR_ERR_HELP                57390
#define AFX_STR_MES_CANCEL              57391

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
